### ISSUE TITLE
Scrollbars disappearing

### ISSUE THREAD

**Issue by Fequois** [humaan/Modaal#1]
#### Issue with scrollsbars

Where scrollbars are visible, like the demo page, the modal will make them disappear. This causes a jump on the content.

Tested on Chrome 50, Windows 10.

To reproduce:

1. Go to the [demo site](http://humaan.com/modaal/)
2. Click 'View Example'
3. Behold, the scrollbar disappears!

**Comment by danhumaan** [comment]
Hi @Fequois,

Thanks for raising the issue. I can replicate what you're seeing and it appears to be a side effect of the plugin applying `overflow: hidden;` to the `<body>`, when it opens. This was to disable the page from scrolling behind while the modal was open.

We're mulling over the most appropriate way forward at the moment, with one solutions being to possibly add an option of `background_scrolling` which would toggle the body overflow on or not.

**Comment by danhumaan** [comment]
Due to this being a browser behaviour when overflow hidden is applied, and the possible DOM manipulation required to maintain the scrollbar but stop the page from scrolling behind, we've decided to implement a new boolean option for `background_scroll`.

The new option defaults to `false` meaning `overflow :hidden` will be applied to the body element. Setting this to true will not apply `overflow :hidden` to the body.
