### ISSUE TITLE
How To: Inserting modal content further up the page

### ISSUE THREAD

**Issue by darylknight** [humaan/Modaal#125]
I've been adding modal functionality to a site primarily aimed at blind users recently, and it's all working really well, except the client just tested it with a screenreader and it's not reading the modal content until it gets to the absolute end of the document, because that's where the `.modaal-wrapper` is being inserted.

They're trying to use this for a donation campaign where this modal opens automatically as soon as the page loads (which works) and reads it to the user before the other content. Is there a way to do this that I'm missing? I'm using this config:

    $('.campaign-modal').modaal({
        content_source: '#inline-modal-content',
        start_open: true,
    });

**Comment by jesseyuen** [comment]
G'day @darylknight 

I've had a little look at this. I don't believe this sort of flexibility is baked into the current config options but have a look in the unminified dist/js/modaal.js file on line [412](https://github.com/humaan/Modaal/blob/3d3abd628620d19dcec5259ee068c855b5a4beeb/dist/js/modaal.js#L412).

Changing the method from `append` to `prepend` moves the modal content to the beginning of the body tag rather than the end. A very quick test with Voice Over suggests you might have some success with this approach!

**Comment by darylknight** [comment]
Thanks for the quick reply! As it turns out, the JAWS tester was just using a lot of shortcuts and skipping the content, so it wasn't a thing in the Modaal that needed fixing. But I appreciate the detailed response.

**Comment by danhumaan** [comment]
thanks @darylknight and @jesseyuen - i hadn't yet had a chance to dive into investigating this issue, but thanks for returning to clarify the cause and outcome
