### ISSUE TITLE
Scrolling on mobile does not have a momentum

### ISSUE THREAD

**Issue by michalsnik** [humaan/Modaal#22]
Scrolling on mobile devices should have a momentum.
In order to achieve so .modaal-wrapper should have:

```
overflow-y: scroll;
webkit-overflow-scrolling: touch;
```

Short article about this: https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

I'm going to make a PR later.

**Comment by cbotman** [comment]
Hi @michalsnik, thanks for flagging this. I quickly tried to implement the solution you described and it didn't work, but I think because of another issue. On my iPhone 6 for example, Modaal isn't trapping focus and the background page is scrolling instead. I suspect when that is fixed, your update will also work.

**Comment by danhumaan** [comment]
Hi @michalsnik, thanks again for your contribution. A fix has been just been rolled out in the [latest release](https://github.com/humaan/Modaal/releases/latest) for this issue.

**Comment by michalsnik** [comment]
Hi @danb-humaan , good work! 👍
