### ISSUE TITLE
Having trouble with "is-locked"

### ISSUE THREAD

**Issue by BMCwebdev** [humaan/Modaal#33]
I cannot seem to get the is-locked option to work for me using the inline data-option-name method. Calling it through a jQuery call does work for me:
```
<script>
    jQuery( document ).ready(function() {
        jQuery('.modaal').modaal({
            is_locked: 'true'
        });
    });
</script>
```

Here is a jsfiddle where I am trying to get it working inline.

https://jsfiddle.net/bmcwebdev/mouvcbgq/

Thanks gang!

**Comment by cbotman** [comment]
Hi @BMCwebdev,

It turns out there are a couple of issues here. 

The first is the code is looking for the inline property "data-modaal-locked" rather than "data-modaal-is-locked". That's the bug, but we'll fix it in a 0.3.x release rather than 0.2.x because it's an API change.

The second is because of how your JSFiddle example is loading in Modaal, there seems to be a problem with the order of events, and Modaal isn't starting up properly. I'm going to open a separate ticket to deal with that.

Thanks for your help!

Regards,
Chris

**Comment by cbotman** [comment]
By the way, here is a fiddle that works in the meantime: https://jsfiddle.net/mouvcbgq/16/

I changed 3 things:

- Replaced data-modaal-is-locked with data-modaal-locked in the HTML.

- Removed this from your JS as it's not relevant:
```
jQuery(document).ready(function() {
        jQuery('.modaal').modaal();
});
```

- In the JavaScript config box, changed the Load Type from 'onLoad to' to 'No wrap - in <body>'. That's because of the aforementioned issue where Modaal doesn't init properly if it's included after onload.

**Comment by cbotman** [comment]
For future self, the fix for this ticket is to just change 'data-modaal-locked' to 'data-modaal-is-locked' in the code. Because this changes the API, we'll put it on 0.3.x.

**Comment by BMCwebdev** [comment]
Perfecto! Thank you cbotman.

**Comment by cbotman** [comment]
No worries @BMCwebdev, you're welcome.
