### ISSUE TITLE
Make .modaal-close:hover color SASS variable

### ISSUE THREAD

**Issue by lewismcarey** [humaan/Modaal#55]
The SASS variables are really handy. 
I think the close hover color is the color I find myself changing the most (yet it isn't set as a SASS variable).

**Comment by danhumaan** [comment]
hi @lewismcarey, thanks for your patience in allowing us time to address this. I've worked in a change as requested and implemented in your pull request, however I won't be accepting or applying your pull request due to a number of other differences that are unrelated and not wanted such as the change to browser prefixes and vendors.

We will roll out the change completed in the coming milestone, so please watch for that implementation then.

**Comment by lewismcarey** [comment]
@danhumaan Thanks for the update and associated implementation.
