### ISSUE TITLE
Using Instagram - Uncaught TypeError: Cannot read property 'Embeds' of undefined

### ISSUE THREAD

**Issue by paulburgess** [humaan/Modaal#72]
Using the modaal for showing instagram popups, everything still works but this error appears in the console: Uncaught TypeError: Cannot read property 'Embeds' of undefined

Refers to line 151:
 window.instgrm.Embeds.process())

I think :-)

**Comment by danhumaan** [comment]
Good pickup, thanks for flagging this @paulburgess  - is this stopping your instance from working? For me it's still working, but I can see the error. Worth investigating, but just trying to determine how much of a prioty this issue is, ie: it's stopping things working vs, it works but throws and error.

**Comment by paulburgess** [comment]
It all seems to works fine. I tried an older version as well and the issue was there too. But you know how it is... that red text staring at you from Deleveloper Tools.

**Comment by danhumaan** [comment]
Ok no worries, thanks @paulburgess - we'll investigate and see what we can do.

**Comment by danhumaan** [comment]
hey @paulburgess, thanks again for raising the issue. I've worked in a fix and pushed it through to our develop branch. Will roll out a new milestone release soon that will have this included.

Leaving this open until we roll out the release, will close it then. Thanks
